version: 0.0

os: linux

files:
  - source: /
    destination: /var/www/
  - source: nginx.conf
    destination: /etc/nginx/
  - source: www.conf
    destination: /etc/php-fpm.d/

file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - directory
      - file

hooks:
  AfterInstall:
    - location: shell/db_init.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: shell/start_server.sh
      timeout: 300
      runas: root
